### ISSUE TITLE
Install net-tools

### ISSUE THREAD

**Issue by webteckie** [million12/docker-centos-supervisor#5]
Are networking tools left out of the image on purpose?  I try to run things like netstat or nmap and these don't seem to be installed.  Having some issues with port connectivity and trying to troubleshoot those.  Thanks for the image by the way!

**Comment by ryzy** [comment]
Hi Carlos!

Thanks for the feedback. Yeah, seems like there were not installed on purpose. Although, after using this image for a while, I agree: `net-tools` could be installed out-of-the-box... I install it sporadically too, to debug this or that and it's very small in terms of size (installed < 1MB).

Not sure about `nmap` though. The `yum install nmap` shows sth like:
```
Total download size: 4.3 M
Installed size: 17 M
```
which is quite substantial and IMO not worth embedding.

**Comment by webteckie** [comment]
Hi Marcin, good enough! Will check it out.  Thanks!
